---
include:
  - board: zitaotech_sofle_left
    shield: lpm_view;left_bbtrackball
  - board: zitaotech_sofle_right
    shield: lpm_view;right_trackpoint



  - board: zitaotech_sofle_left
    shield: lpm_view;left_bbtrackball;settings_reset
  - board: zitaotech_sofle_right
    shield: lpm_view;right_trackpoint;settings_reset
